In [1]:
import numpy
n = numpy.arange(27)

In [6]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [3]:
type(n)

numpy.ndarray

In [7]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [9]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
import cv2

In [18]:
im_g = cv2.imread("smallgray.png",0)

In [19]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [14]:
a=[1,2,3]

In [15]:
a[0:2]

[1, 2]

In [20]:
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [21]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [22]:
im_g.shape

(3, 5)

In [23]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [24]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [25]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [26]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [30]:
ims = numpy.hstack((im_g,im_g,im_g))

In [33]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [36]:
ims = numpy.vstack((im_g,im_g,im_g))

In [37]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [40]:
lst = numpy.hsplit(ims,5)
print(lst)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]


In [41]:
lsv = numpy.vsplit(ims,3)
print(lsv)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
